FROM ghcr.io/kube-pod404/opslora-frontend-service:azure-test-20260609-03

WORKDIR /app

COPY .next ./.next
COPY public ./public
COPY package*.json ./

ENV NODE_ENV=production

EXPOSE 3000

CMD ["npm", "run", "start"]
